CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT UNIQUE NOT NULL,
	user_name TEXT NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
	uuid TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL UNIQUE,
	FOREIGN KEY(user_id) REFERENCES users(id) 
);


CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY,
	title TEXT NOT NULL UNIQUE,
	body TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id) 
);

CREATE TABLE IF NOT EXISTS action (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    vote INTEGER NOT NULL CHECK(vote IN(-1, 1)),
    user_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    UNIQUE (user_id, post_id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(post_id) REFERENCES posts(id),
);
