CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT UNIQUE NOT NULL,
	user_name TEXT NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
	uuid TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL UNIQUE,
	FOREIGN KEY(user_id) REFERENCES users(id) 
);


CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY,
	title TEXT NOT NULL UNIQUE,
	body TEXT NOT NULL,
	actions INTEGER DEFAULT 0, 
	user_id INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id) 
);