CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT UNIQUE NOT NULL,
	user_name TEXT NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
	uuid TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL UNIQUE,
	FOREIGN KEY(user_id) REFERENCES users(id) 
);